# Generated by Django 5.0.4 on 2024-05-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_last_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='last_message_timestamp',
            field=models.BigIntegerField(db_comment='the last message of created at timestmap', default=0, null=True),
        ),
    ]
