version: "3.8"

services:
  apiserver:
    depends_on: 
      - postgres
    container_name: apiserver
    build:
      context: ./apiserver
      dockerfile: Dockerfile
    image:
      apiserver:latest
    ports:
      - 8000:8000
    command: sh -c "/app/entrypoint.sh"
    environment:
      - APP_NAME=apiserver-1
      - APP_PORT=8000
    env_file:
      - apiserver/.env.dev

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres/master:/var/lib/postgresql/data
    env_file:
      - apiserver/.env

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    restart: always
    ports:
      - "8080:8000"
    volumes:
      - ./data/dynamodb:/home/dynamodblocal/data

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_ERLANG_COOKIE: socialmedia
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"
      - "15672:15672"

